<?php

define('PRH_AUTHOR_IMAGE_PATH', 'https://images.randomhouse.com/author/');
define('PRH_AUTHOR_DEFAULT_IMAGE', '/sites/default/files/default-author.png');
define('PRH_COVER_IMAGE_PATH', 'https://images.randomhouse.com/cover/');
define('PRH_COVER_DEFAULT_IMAGE', '/sites/default/files/default-book.png');
/**
 * Settings defaults so we we don't have to change all the variable_get() calls
 * later when I change my mind.
 */
define('ENHANCED_API_DEFAULT_URL', 'https://api.penguinrandomhouse.com/resources/v2/title/domains/');
define('ENHANCED_API_DEFAULT_KEY', 'ebmftcqryd7umzuch262euse');
define('ENHANCED_API_DEFAULT_DOMAIN', 'PRH.CA');
define('ENHANCED_API_DEFAULT_CACHE_TIME', '60');

module_load_include('inc', 'enhanced_api', 'enhanced_api.tokens');
